#!/bin/bash -eu

BRANCH=$(git rev-parse --abbrev-ref HEAD)
if [ "$BRANCH" != "master" ]
then
    echo "I'm sorry $USER, I'm afraid I can't do that"
    echo "Your branch is not master".
else
    yarn build
    git clone https://github.com/pusher/deliverfoo
    cp target/* deliverfoo
    cd deliverfoo
    git add .
    git commit -m "CDN upload"
    git push origin master --force
    cd ..
    rm -rdf deliverfoo
fi
